arduino:
  port: /dev/ttyUSB0
  kind: uno
  pin:
    battery: adc0
    gasPedal: adc1
    stop: D2
    gasPedalSwitch: D3
    keySwitch: D4
    forwardIn: D7
    backwardIn: D8
    speedControlerL: D10
    speedControlerR: D11
    forwardControl: D12
    forwardControl: D13
    indicatorInL: D14
    indicatorInR: D15
    indicatorL: D16
    indicatorR: D17
    lightIn: D18
    light: D19
  
battery:
  voltage: 12
  factor: 3.428
  k: 0.013
  d: 11.7

lane:
  heightmultiplier: 9
  cropmultiplier: 2
  bottommultiplier: 9
  lowend: 50
  highend: 150

usb_cam:
  video_device: /dev/video0
  image_width: 640
  image_height: 480
  pixel_format: yuyv
  camera_frame_id: usb_cam
  io_method: mmap

lidar:
  port: /dev/ttUSB1

steering:
  p: 1
  i: 0.1
  d: 0.5

throttle:
  p: 1
  i: 0.1
  d: 0.5