arduino:
  batteryPin: adc0
  gasPedalPin: adc1
  stopPin: D2
  gasPedalSwitchPin: D3
  keySwitchPin: D4
  forwardInPin: D7
  backwardInPin: D8
  speedControlerL: D10
  speedControlerR: D11
  forwardControlPin: D12
  forwardControlPin: D13
  

battery:
  voltage: 12
  factor: 3.428
  k: 0.013
  d: 11.7

lane:
  heightmultiplier: 9
  cropmultiplier: 2
  bottommultiplier: 9
  lowend: 50
  highend: 150

usb_cam:
  video_device: /dev/video1
