arduino:
  batteryPin: adc0
  gasPedalPin: adc1
  gasPedalSwitchPin: D6
  speedControlerL: D10
  speedControlerR: D11
  forwardLPin: D2
  backwardsLPin: D3
  forwardRPin: D4
  backwardsRPin: D5

battery:
  voltage: 12
  factor: 3.428
  k: 0.013
  d: 11.7

lane:
  heightmultiplier: 9
  cropmultiplier: 2
  bottommultiplier: 9
  lowend: 50
  highend: 150

usb_cam:
  video_device: /dev/video1
