arduino:
  pins:
    battery: adc0
    gasPedal: adc1
    stop: D2
    gasPedalSwitch: D3
    keySwitch: D4
    forwardIn: D7
    backwardIn: D8
    speedControlerL: D10
    speedControlerR: D11
    forwardControl: D12
    forwardControl: D13
  

battery:
  voltage: 12
  factor: 3.428
  k: 0.013
  d: 11.7

lane:
  heightmultiplier: 9
  cropmultiplier: 2
  bottommultiplier: 9
  lowend: 50
  highend: 150

usb_cam:
  video_device: /dev/video1
