arduino:
  port: /dev/arduino0
  pin:
    battery: adc0
    gasPedal: adc1
    speed: adc6
    gasPedalSwitch: D18
    keySwitch: D22
    forwardIn: D26
    backwardIn: D27
    speedControlerL: D4
    speedControlerR: D3
    returnControl: D9
    forwardControl: D10
    indicatorInL: D23
    indicatorInR: D24
    indicatorL: D16
    indicatorR: D17
    lightIn: D25
    stop: D39 #not connected
  
battery:
  voltage: 12
  factor: 3.428
  k: 0.013
  d: 11.7

gaspedal:
  min: 472
  max: 900

lane:
  # canny Edge old (200, 250)
  low_threshold: 200
  high_threshold: 250
  # 50, 150

  # whiteMask
  whiteMaskLow: 180
  whiteMaskHigh: 250

  #ROI
  topWidth: 2
  height: 4
  bottomWidth: 1000
  bottomHeight: 0

usb_cam:
  video_device: /dev/cam0
  image_width: 640
  image_height: 480
  pixel_format: yuyv
  framerate: 25
  camera_frame_id: usb_cam
  io_method: mmap
  fov: 50
  flip_image: True


steering:
  p: 0.5
  i: 0.5
  d: 0.7
  limitLow: -30
  limitHigh: 30

throttle:
  p: 50
  i: 0.001
  d: 2.5
  limitLow: 0
  limitHigh: 50

gui:
  version: v 0.2
  winX: 640
  winY: 480
  fullscreen: False

safety:
  normVelocity: 100.0
  normBreakingDistance: 7.0 # distance at normVelocity in m
  emergencyBreakAngle: 10 # +- angle form 0

rplidarNode:
  serial_port: /dev/lidar0
  serial_baudrate: 115200
  frame_id: laser
  inverted: True
  angle_compensate: True
  

joy:
  deadzone: 0.01
  autorepeat_rate: 1

arduino_main:
  port: /dev/arduino0

arduino_servo:
  port: /dev/arduino1