arduino:
  port: /dev/arduino0
  pin:
    battery: adc0
    gasPedal: adc1
    speed: adc6
    gasPedalSwitch: D18
    keySwitch: D22
    forwardIn: D26
    backwardIn: D27
    speedControlerL: D4
    speedControlerR: D3
    returnControl: D9
    forwardControl: D10
    indicatorInL: D23
    indicatorInR: D24
    indicatorL: D16
    indicatorR: D17
    lightIn: D25
    stop: D39 #not connected
  
battery:
  voltage: 12
  factor: 3.428
  k: 0.013
  d: 11.7

gaspedal:
  min: 472
  max: 900

lane:
  low_threshold: 200
  high_threshold: 250
  whiteMaskLow: 210
  whiteMaskHigh: 255
  topWidth: 10
  height: 2.3
  bottomWidth: 100

usb_cam:
  video_device: /dev/video0
  image_width: 640
  image_height: 480
  pixel_format: yuyv
  camera_frame_id: usb_cam
  io_method: mmap
  fov: 50
  flip_image: True


steering:
  p: 1
  i: 0.1
  d: 0.5

throttle:
  p: 10
  i: 0.1
  d: 1.0

gui:
  version: v 0.2
  winX: 640
  winY: 480
  fullscreen: False

safety:
  normVelocity: 10
  normBreakingDistance: 2 # distance at normVelocity in m
  emergencyBreakAngle: 10 # +- angle form 0